#
#Sat May 02 16:12:59 COT 2026
goog\:chromeOptions={args\=[remote-allow-origins\=*, --start-maximized, --incognito, --disable-notifications, --disable-infobars, --disable-save-password-bubble, --disable-features\=PasswordLeakDetection,PasswordCheck], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
